"""empty message

Revision ID: ab6f3b102dac
Revises: d115eb7f2770
Create Date: 2020-02-19 21:22:06.625779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6f3b102dac'
down_revision = 'd115eb7f2770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Customer_address', table_name='Customer')
    op.create_index(op.f('ix_Customer_address'), 'Customer', ['address'], unique=False)
    op.drop_index('ix_Customer_age', table_name='Customer')
    op.create_index(op.f('ix_Customer_age'), 'Customer', ['age'], unique=False)
    op.drop_index('ix_Customer_email', table_name='Customer')
    op.create_index(op.f('ix_Customer_email'), 'Customer', ['email'], unique=False)
    op.drop_index('ix_Customer_first_name', table_name='Customer')
    op.create_index(op.f('ix_Customer_first_name'), 'Customer', ['first_name'], unique=False)
    op.drop_index('ix_Customer_gender', table_name='Customer')
    op.create_index(op.f('ix_Customer_gender'), 'Customer', ['gender'], unique=False)
    op.drop_index('ix_Customer_last_name', table_name='Customer')
    op.create_index(op.f('ix_Customer_last_name'), 'Customer', ['last_name'], unique=False)
    op.drop_index('ix_Customer_phoneNumber', table_name='Customer')
    op.create_index(op.f('ix_Customer_phoneNumber'), 'Customer', ['phoneNumber'], unique=False)
    op.drop_index('ix_Customer_registerationDate', table_name='Customer')
    op.create_index(op.f('ix_Customer_registerationDate'), 'Customer', ['registerationDate'], unique=False)
    op.drop_index('ix_Customer_state', table_name='Customer')
    op.create_index(op.f('ix_Customer_state'), 'Customer', ['state'], unique=False)
    op.drop_index('ix_Customer_zipcode', table_name='Customer')
    op.create_index(op.f('ix_Customer_zipcode'), 'Customer', ['zipcode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Customer_zipcode'), table_name='Customer')
    op.create_index('ix_Customer_zipcode', 'Customer', ['zipcode'], unique=True)
    op.drop_index(op.f('ix_Customer_state'), table_name='Customer')
    op.create_index('ix_Customer_state', 'Customer', ['state'], unique=True)
    op.drop_index(op.f('ix_Customer_registerationDate'), table_name='Customer')
    op.create_index('ix_Customer_registerationDate', 'Customer', ['registerationDate'], unique=True)
    op.drop_index(op.f('ix_Customer_phoneNumber'), table_name='Customer')
    op.create_index('ix_Customer_phoneNumber', 'Customer', ['phoneNumber'], unique=True)
    op.drop_index(op.f('ix_Customer_last_name'), table_name='Customer')
    op.create_index('ix_Customer_last_name', 'Customer', ['last_name'], unique=True)
    op.drop_index(op.f('ix_Customer_gender'), table_name='Customer')
    op.create_index('ix_Customer_gender', 'Customer', ['gender'], unique=True)
    op.drop_index(op.f('ix_Customer_first_name'), table_name='Customer')
    op.create_index('ix_Customer_first_name', 'Customer', ['first_name'], unique=True)
    op.drop_index(op.f('ix_Customer_email'), table_name='Customer')
    op.create_index('ix_Customer_email', 'Customer', ['email'], unique=True)
    op.drop_index(op.f('ix_Customer_age'), table_name='Customer')
    op.create_index('ix_Customer_age', 'Customer', ['age'], unique=True)
    op.drop_index(op.f('ix_Customer_address'), table_name='Customer')
    op.create_index('ix_Customer_address', 'Customer', ['address'], unique=True)
    # ### end Alembic commands ###
