"""empty message

Revision ID: b9b702afb147
Revises: ab6f3b102dac
Create Date: 2020-02-20 11:34:47.950496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b702afb147'
down_revision = 'ab6f3b102dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('age', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('zipcode', sa.String(length=120), nullable=True),
    sa.Column('phoneNumber', sa.String(length=120), nullable=True),
    sa.Column('registerationDate', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Customer_address'), 'Customer', ['address'], unique=False)
    op.create_index(op.f('ix_Customer_age'), 'Customer', ['age'], unique=False)
    op.create_index(op.f('ix_Customer_email'), 'Customer', ['email'], unique=False)
    op.create_index(op.f('ix_Customer_first_name'), 'Customer', ['first_name'], unique=False)
    op.create_index(op.f('ix_Customer_gender'), 'Customer', ['gender'], unique=False)
    op.create_index(op.f('ix_Customer_last_name'), 'Customer', ['last_name'], unique=False)
    op.create_index(op.f('ix_Customer_phoneNumber'), 'Customer', ['phoneNumber'], unique=False)
    op.create_index(op.f('ix_Customer_registerationDate'), 'Customer', ['registerationDate'], unique=False)
    op.create_index(op.f('ix_Customer_state'), 'Customer', ['state'], unique=False)
    op.create_index(op.f('ix_Customer_zipcode'), 'Customer', ['zipcode'], unique=False)
    op.create_table('Template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=64), nullable=True),
    sa.Column('para1', sa.String(length=120), nullable=True),
    sa.Column('para2', sa.String(length=128), nullable=True),
    sa.Column('para3', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Template')
    op.drop_index(op.f('ix_Customer_zipcode'), table_name='Customer')
    op.drop_index(op.f('ix_Customer_state'), table_name='Customer')
    op.drop_index(op.f('ix_Customer_registerationDate'), table_name='Customer')
    op.drop_index(op.f('ix_Customer_phoneNumber'), table_name='Customer')
    op.drop_index(op.f('ix_Customer_last_name'), table_name='Customer')
    op.drop_index(op.f('ix_Customer_gender'), table_name='Customer')
    op.drop_index(op.f('ix_Customer_first_name'), table_name='Customer')
    op.drop_index(op.f('ix_Customer_email'), table_name='Customer')
    op.drop_index(op.f('ix_Customer_age'), table_name='Customer')
    op.drop_index(op.f('ix_Customer_address'), table_name='Customer')
    op.drop_table('Customer')
    # ### end Alembic commands ###
