"""empty message

Revision ID: d20bcab1d029
Revises: f54f3d7441db
Create Date: 2020-02-18 18:11:01.442694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20bcab1d029'
down_revision = 'f54f3d7441db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=64), nullable=True),
    sa.Column('para1', sa.String(length=120), nullable=True),
    sa.Column('para2', sa.String(length=128), nullable=True),
    sa.Column('para3', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Title'),
    sa.UniqueConstraint('para1')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Template')
    # ### end Alembic commands ###
