"""empty message

Revision ID: f54f3d7441db
Revises: c6baf9c8790e
Create Date: 2020-02-18 18:08:23.251209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54f3d7441db'
down_revision = 'c6baf9c8790e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='template_pkey')
    )
    # ### end Alembic commands ###
